USE tavak;
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (1, "Gyova-Mámai-Holt-Tisza", "morotvató", 1.33, 35);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (2, "Abaligeti-horgásztó", "mesterséges", 0.025);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (3, "Délegyházi-tavak", "bányató", 3.38, 3);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (4, "Öregállás III. tó", "", 0.98, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (5, "Serházzugi-Holt-Tisza", "morotvató", 1.34, 9);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (6, "Palotási-tározó", "mesterséges", 0.58, 57);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (7, "Csongrádi-Bokrosi-Sós-tó", "morotvató", 1.21, 6);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (8, "Csór-réti-víztározó", "mesterséges", 0.12, 8);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (9, "Tunyogmatolcsi-tározó", "", 1.93, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (10, "Tiszadobi-Holt-Tisza", "morotvató", 1.03, 208);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (11, "Rakacai-víztározó", "mesterséges", 1.9, 235);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (12, "Sárszentágotai-sóstó", "szikes tó", 0.52, 3);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (13, "Csorbatelepi-tó", "", 1.01, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (14, "Somogycsicsói-halastavak", "", 0.51, 39);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (15, "Peresi-holtágrendszer (Kecskészugi-, Templomzugi-, Bónomzugi-, Soczózugi-, Peresi-holtág)", "morotvató", 2.16, 240);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (16, "Fehér-szíki-tározó", "mesterséges", 1.46, 11);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (17, "Ladomány II. és III. számú halastó", "", 1.05, 82);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (18, "Hortobágyi-öregtavak", "", 16.48, 16);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (19, "Korcsánypusztai-halastavak", "", 0.56, 11);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (20, "Anyácsai-tó", "", 0.02);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (21, "X. tározó", "mesterséges", 1.39, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (22, "Bátai-holtág", "morotvató", 0.66, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (23, "Nagyigmándi-halastavak", "", 0.62, 116);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (24, "Mikei-halastórendszer", "", 0.71, 67);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (25, "Nagyfai-Holt-Tisza", "morotvató", 0.67, 6);
INSERT INTO alloviz (id, nev, tipus) VALUES (26, "Hermann Ottó-tó", "mesterséges");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (27, "Oláhréti-víztározó", "mesterséges", 0.57, 2);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (28, "Biharugrai-halastavak", "", 7.38, 7);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (29, "Bogyiszlói-Holt-Duna", "morotvató", 0.5, 16);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (30, "Palkonyai-halastavak", "", 0.92, 61);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (31, "Zámolyi-tározó", "", 1.69, 255);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (32, "Alcsi-Holt-Tisza", "morotvató", 1.62, 115);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (33, "Tisza-tó", "mesterséges", 120.83, 8);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (34, "Pécsi-tó", "mesterséges", 0.79, 32);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (35, "Gödöllői-halastavak", "", 0.6, 38);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (36, "Félhalmi-holtágrendszer (Félhalmi-, Danzugi-, Torzsási-holtág)", "morotvató", 0.73, 57);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (37, "Vajdácskai hullámtéri holtágak", "morotvató", 0.78, 90);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (38, "Kiskondai-halastavak", "", 2.57, 70);
INSERT INTO alloviz (id, nev) VALUES (39, "Kislóki-tó");
INSERT INTO alloviz (id, nev, tipus) VALUES (40, "Vörös-tó", "karsztos");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (41, "Csele-halastó", "", 0.6, 77);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (42, "Cibakházi-Holt-Tisza", "morotvató", 2.56, 72);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (43, "Kisteleki-Müller-szék", "szikes tó", 0.87, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (44, "Sárszentmihályi-tározó", "mesterséges", 1.03, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (45, "Lipóti-morotvató", "morotvató", 0.56, 2);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (46, "Ráckevei-Soroksári-Dunaág", "morotvató", 15.58, 832);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (47, "Szelidi-tó", "morotvató", 0.52, 401);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (48, "Attala-Inámi-halastórendszer", "", 1.74, 109);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (49, "Vértó", "", 0.027);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (50, "Kiskunhalasi Sós-tó", "szikes tó", 0.55, 2);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (51, "Mátételki-tározó", "mesterséges", 0.83, 188);
INSERT INTO alloviz (id, nev, tipus) VALUES (52, "Dávodi-Földvár-tó", "morotvató");
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (53, "Bánki-tó", "mesterséges", 0.079);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (54, "Madarász-tó", "", 0.77, 4);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (55, "Bába-szék", "szikes tó", 1.26, 22);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (56, "Ártándi-kavicsbányató", "bányató", 0.94, 1);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (57, "Bodajki-tó", "", 0.0022);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (58, "Tatai-Öreg-tó", "mesterséges", 2.07, 23);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (59, "Iregszemcsei-Nagykónyi-tározók", "mesterséges", 1.21, 70);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (60, "Nagyvadas-tó", "", 1.35, 5);
INSERT INTO alloviz (id, nev, tipus) VALUES (61, "Abaligeti Csónakázó-tó", "mesterséges");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (62, "Boki-holtág", "morotvató", 0.65, 5);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (63, "Tolnai-Déli-Holt-Duna", "morotvató", 1.34, 109);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (64, "Ongai-kavicsbányatavak", "bányató", 0.56, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (65, "Délegyháza-I.", "bányató", 0.7, 1);
INSERT INTO alloviz (id, nev, tipus) VALUES (66, "Arlói-tó", "suvadás");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (67, "Fertő-tó", "szélvájta", 75.41, 1493);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (68, "Hegyeshalmi-kavicsbányató", "bányató", 0.77, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (69, "Csertői-halastó", "", 1.16, 165);
INSERT INTO alloviz (id, nev) VALUES (70, "Gőtés-tó");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (71, "Ősze-szék", "szikes tó", 0.72, 2);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (72, "Bácsbokodi-Felsőszentiváni-halastavak", "", 0.66, 114);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (73, "Pölöskei K-i tározó", "mesterséges", 1.24, 1);
INSERT INTO alloviz (id, nev) VALUES (74, "Sárkány-tó");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (75, "Mátrai Erőmű tavai", "mesterséges", 0.58, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (76, "Matyéri-tározó", "", 0.69, 3);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (77, "Rinyaszentkirályi-halastórendszer", "", 0.64, 49);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (78, "Mocsai-kavicsbánya-tavak", "bányató", 0.53, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (79, "Laskóvölgyi-víztározó", "mesterséges", 1.24, 91);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (80, "Vasúti (Velence) kavicsbánya", "bányató", 1.64, 92);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (81, "Maconkai-víztározó", "mesterséges", 0.58);
INSERT INTO alloviz (id, nev, tipus) VALUES (82, "Városligeti-tó", "mesterséges");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (83, "Alpári-Holt-Tisza és Szikra-Holt-Tisza", "morotvató", 2.26, 331);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (84, "Búvár-tó", "", 0.03);
INSERT INTO alloviz (id, nev, tipus) VALUES (85, "Tagi bányató", "bányató");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (86, "Fegyverneki-Holt-Tisza", "morotvató", 1.41, 125);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (87, "Köszörű-völgyi-víztározó", "mesterséges", 0.04, 6);
INSERT INTO alloviz (id, nev, tipus) VALUES (88, "Malom-tó", "forrástó");
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (89, "Hévízi-tó", "forrástó", 0.046);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (90, "Pannónia-tó", "", 0.1941);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (91, "Tamási Fürgedi- és Kecsegei-árkon lévő tavak", "", 1.19, 676);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (92, "Harangzugi-Holt-Körös", "morotvató", 0.53, 386);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (93, "Kolon-tó", "szélvájta", 8.97, 300);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (94, "Harangodi-tározó", "mesterséges", 1.38, 210);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (95, "Dombay-tó", "mesterséges", 0.013);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (96, "Riha-tó", "morotvató", 1.42, 4);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (97, "Házirélti-víztározó", "mesterséges", 0.026);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (98, "Alsózsolcai I. kavicsbánya", "bányató", 0.9, 1);
INSERT INTO alloviz (id, nev, tipus) VALUES (99, "Slötyi", "mesterséges");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (100, "Balaton", "tektonikus", 594.26, 5758);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (101, "Belső-Béda-holtág", "morotvató", 0.83, 76);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (102, "Desedai-tározó", "mesterséges", 2.46, 166);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (103, "Gyálai-Holt-Tisza", "morotvató", 1.64, 622);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (104, "Tiszacsegei-Holt-Tisza", "morotvató", 0.88, 99);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (105, "Csokonyavisontai-halastórendszer", "", 0.68, 35);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (106, "Gébárti-tó", "mesterséges", 0.31);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (107, "Kis-Balaton I. tározó", "mesterséges", 19.65, 1861);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (108, "Bokodi-hűtőtó", "mesterséges", 1.75, 118);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (109, "Naplás-tó", "mesterséges", 1.5);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (110, "Cseke-tó", "mesterséges", 0.18);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (111, "I-II-III. tó", "mesterséges", 1.71, 2);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (112, "Kamarás-Duna", "morotvató", 0.64, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (113, "Nagykarácsonyi-halastó", "", 1.1, 182);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (114, "Császár-éri-halastavak", "", 0.54, 31);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (115, "Kökényi-tó", "mesterséges", 0.09);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (116, "Devecseri (Székpusztai)-tározó", "mesterséges", 0.56, 64);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (117, "Grébeci-Holt-Duna", "morotvató", 0.53, 1);
INSERT INTO alloviz (id, nev, tipus) VALUES (118, "Megyer-hegyi tengerszem", "bányató");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (119, "Kardoskúti Fehér-tó", "szikes tó", 1, 13);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (120, "Ferencmajori-tavak", "", 3.7);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (121, "Szegedi Fehér-tó", "szikes tó", 14.48, 16);
INSERT INTO alloviz (id, nev) VALUES (122, "Jávor-tó");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (123, "Értényi-halastavak", "", 0.68, 26);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (124, "Várpalotai bányasüllyedékes tavak", "bányató", 3.72, 80);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (125, "Zab-szék", "szikes tó", 1.22, 4);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (126, "Kecskeri-tározó", "mesterséges", 1.56, 2);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (127, "Nagy-Széksóstó", "szikes tó", 0.98, 217);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (128, "Varsádi-halastavak", "", 1.95, 4);
INSERT INTO alloviz (id, nev, tipus) VALUES (129, "Gátéri-Fehér-tó", "mesterséges");
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (130, "Határréti-víztározó", "mesterséges", 0.079);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (131, "I. tó", "", 0.98, 1);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (132, "Merzsán-tó", "", 0.075);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (133, "Hősök tava", "mesterséges", 0.22);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (134, "Malomvölgyi 2-es tó", "mesterséges", 0.2);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (135, "Körtvélyesi-Holt-Tisza", "morotvató", 0.58, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (136, "Vadkerti-tó (Nagy-Büdös-tó)", "szikes tó", 0.73, 150);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (137, "Marcali-vízminőség-szabályozó-halastórendszer", "", 4.03, 243);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (138, "Külső-Béda", "morotvató", 0.67, 15);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (139, "Kelemenszék", "szikes tó", 1.34, 6);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (140, "Faddi-Holt-Duna", "morotvató", 2.48, 210);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (141, "Abért-tó (Kőszeg-Lukácsházi víztározó)", "", 0.25);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (142, "Nagy-Morotva", "morotvató", 0.92, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (143, "Somogyapáti-halastó", "", 0.96, 56);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (144, "Tiszaugi-Holt-Tisza", "morotvató", 0.62, 65779);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (145, "Lovászhetényi 1-2-3-4-5-11 számú halastavak", "", 0.64, 73);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (146, "Garancsi-tó", "", 0.02);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (147, "Nagyszéki-tó", "szikes tó", 1, 12);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (148, "Tripolisz", "", 0.74, 28);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (149, "Komra-völgyi-tározó", "", 0.45, 6);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (150, "Hámori-tó", "mesterséges", 0.106);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (151, "Cserőközi-Holt-Tisza", "morotvató", 0.41, 13);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (152, "Nyékládháza-kavicsbányák", "bányató", 4.76, 5);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (153, "Szajoli-Holt-Tisza", "morotvató", 0.7, 35);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (154, "Sándorfalvi-halastavak", "", 5.82, 7);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (155, "Baláta-tó", "", 4.48);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (156, "Mezőlaki-tőzegbánya-tavak", "bányató", 0.94, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (157, "Békéscsaba Téglagyári-tavak", "bányató", 1.14, 1);
INSERT INTO alloviz (id, nev, tipus) VALUES (158, "Vadása-tó", "mesterséges");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (159, "Szamossályi-tározó", "mesterséges", 0.57, 8);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (160, "Péteri-tó", "szikes tó", 2.15, 4);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (161, "Tiszatarjáni-Holt-Tisza", "morotvató", 0.69, 32);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (162, "Pilisvörösvári-tórendszer", "bányató", 0.32);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (163, "Kenézi-morotva", "morotvató", 0.52, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (164, "Tiszaluci-Holt-Tisza", "morotvató", 1.48, 41);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (165, "Böddi-szék", "szikes tó", 6.68, 16);
INSERT INTO alloviz (id, nev) VALUES (166, "Bábaréti-tó");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (167, "Adácsi-víztározó", "mesterséges", 0.52, 1);
INSERT INTO alloviz (id, nev, tipus) VALUES (168, "Tóstrand", "mesterséges");
INSERT INTO alloviz (id, nev) VALUES (169, "Bük-Bő-Gór-víztározó");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (170, "Pátkai-tározó", "mesterséges", 2.86, 357);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (171, "II. Spicvald", "", 1.22, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (172, "Kispodári-tározó", "mesterséges", 0.53, 108);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (173, "Vidre-éri halastavak", "", 0.74, 2);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (174, "Buzsáki-halastavak", "", 1.23, 176);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (175, "Vajai-tározó", "", 0.67, 89);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (176, "Palatinus-tó", "bányató", 0.32);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (177, "Lupa-szigeti bányatavak", "bányató", 0.87, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (178, "Halásztelek-Túrtő-Harcsás-Holt-Körös", "morotvató", 1.29, 48);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (179, "Rukkel-tó", "bányató", 0.12);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (180, "Fancsika-I. tározó", "mesterséges", 0.85, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (181, "Öregállás II. tó", "", 1.33, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (182, "Kanyari-Holt-Tisza", "morotvató", 0.49, 7);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (183, "Tiszakécskei-Holt-Tisza", "morotvató", 1.18, 290);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (184, "Lábodi-halastórendszer", "", 1.07, 18);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (185, "Kotró", "bányató", 3.2);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (186, "Pusztaszeri-Büdös-szék", "szikes tó", 0.62, 3);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (187, "Kis-Balaton II. tározó", "mesterséges", 51.51, 2587);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (188, "Begécsi-halastavak", "", 11.79, 12);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (189, "Nagy-szik", "szikes tó", 0.73, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (190, "L-I. tározó", "", 0.7, 80);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (191, "Feneketlen-tó", "bányató", 0.011);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (192, "Öregállás V. tó", "", 0.77, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (193, "Szálkai-tározó", "", 0.66, 23);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (194, "Atkai-Holt-Tisza", "morotvató", 1.09, 62);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (195, "Fehérvárcsurgói-tározó", "mesterséges", 1.44, 266);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (196, "Alsómocsoládi-halastórendszer", "", 1.47, 79);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (197, "Markazi-víztározó", "mesterséges", 1.62, 11);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (198, "Nagybaracskai-Holt-Duna", "morotvató", 0.82, 26);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (199, "Bodrogközi hullámtéri holtágak", "morotvató", 1.85, 210);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (200, "Leveleki-víztározó", "mesterséges", 1.64, 177);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (201, "Töröcskei-tó", "mesterséges", 0.115);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (202, "Rétközi-tó", "", 3.39, 6);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (203, "Hórvölgyi-víztározó", "mesterséges", 1.41, 153);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (204, "Kakasszéki-tó", "", 0.54, 42);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (205, "Naszály–Grébicsi-halastavak", "", 1.05, 58);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (206, "Hasznosi-tározó", "mesterséges", 0.22, 36);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (207, "Lázbérci-víztározó", "mesterséges", 0.71, 213);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (208, "Nagybaráti-halastó", "", 0.64, 113);
INSERT INTO alloviz (id, nev, tipus) VALUES (209, "Rüdiger-tó", "mesterséges");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (210, "Csaj-tó", "", 9.65, 53);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (211, "Egyeki-Holt-Tisza", "morotvató", 0.87, 28);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (212, "Kistormási-halastavak", "", 0.64, 110);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (213, "György-éri-halastavak", "", 0.99, 5);
INSERT INTO alloviz (id, nev, tipus) VALUES (214, "Orfűi-tó", "mesterséges");
INSERT INTO alloviz (id, nev) VALUES (215, "Sástó");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (216, "Csónakázó-tó", "", 0.55, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (217, "K-XI tározó", "mesterséges", 1.55, 2);
INSERT INTO alloviz (id, nev, tipus) VALUES (218, "Aggteleki-tó", "karsztos");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (219, "Merenyei-halastó", "", 1.03, 99);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (220, "Bokrosi-tó", "", 1.14, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (221, "Nagy-nyomás", "", 0.83, 6);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (222, "Szabadszállási-Büdös-szék", "szikes tó", 0.51, 11);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (223, "Ostorosi-víztározó", "mesterséges", 0.3);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (224, "Harkai-tó", "", 1.36, 5);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (225, "Zalaszentmihályi-horgásztó", "", 0.88, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (226, "Szamosmenti-tározó", "mesterséges", 1.43, 5);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (227, "Péri-halastavak", "", 0.79, 99);
INSERT INTO alloviz (id, nev, tipus, terulet) VALUES (228, "Jenői-tó", "mesterséges", 0.38);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (229, "Gálosfai-horgásztavak", "", 0.56, 32);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (230, "Nagyréti-víztározó", "mesterséges", 2.17, 3);
INSERT INTO alloviz (id, nev, tipus) VALUES (231, "Kovácsszénájai-tó", "mesterséges");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (232, "Cikolai-tavak", "morotvató", 0.91, 221);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (233, "Tolnai-Északi-Holt-Duna", "morotvató", 1.56, 94);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (234, "Hársasberki-halastó", "", 2.42, 111);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (235, "Velencei-tó", "tektonikus", 24.32, 882);
INSERT INTO alloviz (id, nev, tipus) VALUES (236, "Rudabányai-tó", "bányató");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (237, "Tamási Gonozdi-patakon lévő halastavak", "", 1, 76);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (238, "Hegyesdi-tározó", "mesterséges", 0.83, 263);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (239, "Mesztegnyői-halastórendszer", "", 0.63, 41);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (240, "Kadia-Ó-Duna", "morotvató", 0.59, 188);
INSERT INTO alloviz (id, nev, tipus) VALUES (241, "Zichy-tó", "mesterséges");
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (242, "Pötrétei-tőzegbányatavak", "bányató", 3.34, 3);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (243, "Boldogasszonypusztai-tavak", "", 1.17, 49);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (244, "Szalkszentmártoni-kavicsbányatavak", "bányató", 0.54, 1);
INSERT INTO alloviz (id, nev, tipus, terulet, vizgyujto) VALUES (245, "Szarvas-Békésszentandrási-holtágrendszer (Siratói- és Békésszentandrási-holtág)", "morotvató", 2.07, 1132);
