var keresztnev = "Polyák";
console.log(keresztnev);
var vezeteknev = "Szilike";
console.log(vezeteknev);
var kor = 32;
var nagykoru = false;
console.log(nagykoru);
var magassag;
console.log(magassag);
console.log(nemletezo);