USE fuszerkeverek;
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (1, "Aglio-olio", 290, 20, "Magyarország", "Olasz, tésztás ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (2, "Almás pite", 290, 20, "Magyarország", "Almás sütemények töltelékének ízesítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (3, "Argentin", 290, 20, "Magyarország", "Sült húsokhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (4, "Baharat", 290, 20, "Magyarország", "");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (5, "Bami goreng", 290, 20, "Magyarország", "Indonéz jellegű ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (6, "Bárány", 290, 20, "Magyarország", "Sült húsokhoz, ragukhoz, elsősorban bárányhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (7, "Barbecue", 290, 20, "Magyarország", "Grillhúsok pácolásához, sült húsok ízesítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (8, "Biriyani masala", 290, 20, "Magyarország", "Indiai ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (9, "Bolognai", 290, 20, "Magyarország", "Paradicsomos szószokhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (10, "Borneói vaníliás bors", 900, 10, "Németország", "Halakhoz, mártásokhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (11, "Cajun", 320, 20, "Magyarország", "Sült húsokhoz, grillezéshez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (12, "Chili con carne", 290, 20, "Magyarország", "Chilis bab készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (13, "Citromos bors", 290, 20, "Magyarország", "Halakhoz, mártásokhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (14, "Creol", 290, 20, "Magyarország", "Sült húsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (15, "Curry", 260, 20, "Magyarország", "Indiai ételek ízesítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (16, "Curry angol", 290, 20, "Németország", "Indiai raguk ízesítéséhez ajánlott fűszerkeverék.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (17, "Curry colombo", 290, 20, "Magyarország", "Indiai ételek ízesítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (18, "Curry csípős", 290, 20, "Magyarország", "Csípős indiai ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (19, "Curry édeskés", 290, 20, "Magyarország", "Édes jellegű indiai ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (20, "Curry enyhén csípős", 290, 20, "Magyarország", "Enyhén csípős indiai ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (21, "Curry madras", 290, 20, "Magyarország", "Indiai ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (22, "Currys csirke", 290, 20, "Magyarország", "Indiai ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (23, "Cseréptálban sültek", 290, 20, "Magyarország", "Sült húsok, zöldségek ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (24, "Csípős csirkeszárny", 290, 20, "Magyarország", "Csirkeszárnyak ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (25, "Csirkekirály", 290, 20, "Magyarország", "Szárnyas húsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (26, "Ételízesítő glutamát nélkül", 290, 50, "Magyarország", "Levesekhez, sült húsokhoz, ragukhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (27, "Fajita", 290, 20, "Magyarország", "Mexikói jellegű ételek és grillezett húsok, halak fűszerezésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (28, "Fasírt", 290, 20, "Magyarország", "Fasírtok, húsgolyók, darált húsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (29, "Fincsibe", 290, 20, "Magyarország", "Sült szárnyas húsokhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (30, "Flekken", 290, 30, "Magyarország", "Sült húsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (31, "Fokhagymás bors", 290, 20, "Magyarország", "Sült húsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (32, "Fokhagymás só", 230, 30, "", "Sült húsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (33, "Forralt fehérbor", 350, 20, "Magyarország", "Forralt fehérbor készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (34, "Forraltbor", 350, 20, "Magyarország", "1-1,5 l forralt bor készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (35, "Forraltbor fűszerkeverék ajándék üvegben", 1650, 100, "Magyarország", "7-8 l forralt bor készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (36, "Forraltbor gyümölcsös", 350, 20, "Magyarország", "1-1,5 l forralt bor készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (37, "Füstsó", 290, 30, "Magyarország", "Sült húsok, raguk készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (38, "Fűszervaj", 290, 20, "Magyarország", "Szárnyas húsok, tészták ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (39, "Garam masala egész", 290, 20, "Magyarország", "Indiai ételek elkészítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (40, "Garam masala őrölt", 290, 20, "Magyarország", "Indiai ételek elkészítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (41, "Goa masala", 290, 20, "Magyarország", "Indiai jellegű ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (42, "Gourmet tarkabors", 470, 20, "Magyarország", "Bármilyen ételhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (43, "Görög saláta", 290, 20, "Magyarország", "Saláták fűszerezéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (44, "Grill", 290, 20, "Magyarország", "Grillhúsok, zöldségek ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (45, "Grillbors", 290, 20, "Magyarország", "Grillhúsok, zöldségek ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (46, "Grillcsirke", 290, 20, "Magyarország", "Sült csirke illetve csirkecomb készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (47, "Grillzöldség", 290, 20, "Magyarország", "Grillzöldségek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (48, "Gulyás", 290, 20, "Magyarország", "Gulyásleves ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (49, "Gyros", 290, 20, "Magyarország", "Sült húsok és gyros készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (50, "Gyümölcsleves", 290, 20, "Magyarország", "Gyümölcsleves készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (51, "Hét tenger curry", 290, 20, "Magyarország", "Indiai ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (52, "Hétfűszer", 290, 20, "Magyarország", "Saláták, sült zöldségek, főzelékek ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (53, "Indiai bárány", 290, 20, "Magyarország", "Indiai jellegű bárányhúsból készült ételek elkészítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (54, "Indiai ötfűszer", 290, 20, "Magyarország", "Lencsés, zöldséges, indiai jellegű ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (55, "Indiai szárnyas", 290, 20, "Magyarország", "Indiai jellegű ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (56, "Kacsasült", 290, 20, "Magyarország", "Szárnyashúsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (57, "Kansas grill", 290, 20, "Magyarország", "Barbecue-hoz, grillezéshez, sült húsok készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (58, "Karácsonyi sütemény", 290, 20, "Magyarország", "Mézeskalácshoz vagy karácsonyi süteményekhez");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (59, "Kasmír masala", 290, 20, "Magyarország", "Indiai jellegű ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (60, "Kínai", 290, 20, "Magyarország", "Távol keleti ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (61, "Kínai csípős", 290, 20, "Magyarország", "Csípős, távol keleti ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (62, "Kínai halfűszer", 290, 20, "Magyarország", "Halakhoz és kínai ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (63, "Kínai hétfűszer", 290, 20, "Magyarország", "Távol keleti ételekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (64, "Kínai ötfűszer", 290, 20, "Magyarország", "Sültekhez, ragukhoz, süteményekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (65, "Krétai fűszerkeverék vadon termő", 390, 10, "Kréta", "Különleges, intenzív ízű fűszerkeverék, mely kiváló salátákhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (66, "Lazac-steak", 290, 20, "Magyarország", "Halak ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (67, "Leves lelke", 290, 20, "Magyarország", "Levesekhez, konfitált húsokhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (68, "Libasült", 290, 20, "Magyarország", "Szárnyashúsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (69, "Magyaros", 290, 20, "Magyarország", "Pörköltek, raguk ízesítésére");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (70, "Magyaros grillpác", 290, 25, "Magyarország", "Grillhúsok pácolásához.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (71, "Májgombóc", 290, 20, "Magyarország", "Májgombóc ízesítésére");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (72, "Marokkói csirke", 290, 20, "Magyarország", "Csirkehús fűszerezésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (73, "Mártogatós", 290, 20, "Magyarország", "Joghurthoz, tejfölhöz adva mártogatósként zöldségek, chipsek mellé.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (74, "Mediterrán zöldfűszer", 290, 20, "Magyarország", "Salátafűszerként.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (75, "Mexikói", 290, 20, "Magyarország", "Mexikói raguk ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (76, "Mézeskalács ", 290, 20, "Magyarország", "Mézeskalácshoz vagy mézes jellegű süteményekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (77, "Mézessütemény", 290, 20, "Magyarország", "Mézeskalácshoz vagy mézes jellegű süteményekhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (78, "Mucho macho", 290, 20, "Magyarország", "Csípős sült húsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (79, "Mustáros karaj", 290, 20, "Magyarország", "Sült sertéshús fűszerezésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (80, "Négyfűszer", 290, 20, "Magyarország", "Saláták fűszerezésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (81, "Nyárspolgár bbq rub francia", 1500, 225, "Magyarország", "Sertéshez, szárnyashoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (82, "Nyárspolgár bbq rub joker", 1500, 225, "Magyarország", "Bármilyen húsféléhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (83, "Nyárspolgár bbq rub texasi kávés", 1500, 225, "Magyarország", "Marhához, sertéshez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (84, "Olasz", 290, 10, "Magyarország", "Olaszos ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (85, "Oldalas", 290, 20, "Magyarország", "Sült húsok ízesítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (86, "Ördög hozta csirke", 290, 20, "Magyarország", "Csípős, szárnyashúsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (87, "Paella", 290, 20, "Magyarország", "Paella készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (88, "Pástétom", 290, 20, "Magyarország", "Pástétomok, húskrémek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (89, "Pecsenye-grill-steak", 290, 20, "Magyarország", "Sült húsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (90, "Pizza", 290, 10, "Magyarország", "Olaszos tészták, raguk ízesítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (91, "Pokol", 290, 20, "Magyarország", "Csípős húsok ízesítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (92, "Provence", 290, 10, "Magyarország", "Saláták, raguk fűszerezésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (93, "Rák és hal", 290, 20, "Magyarország", "Rákok, halak ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (94, "Rizsfűszer", 290, 20, "Magyarország", "Rizs főzéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (95, "Rozmaringos sült zöldség", 290, 20, "Magyarország", "Sült zöldségek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (96, "Rozmaringos sültburgonya", 290, 30, "Magyarország", "Rozmaringos steakburgonya készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (97, "Sajt és túró", 290, 10, "Magyarország", "Sajt-, és túrókrém készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (98, "Saláta", 290, 10, "Magyarország", "Saláták fűszerezésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (99, "Sertésropogós", 290, 20, "Magyarország", "Ropogós sertéssült készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (100, "Sertéssült", 290, 30, "Magyarország", "Sült sertéshús készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (101, "Shichimi togarashi", 800, 20, "Magyarország", "Sültekhez, rizshez, zöldséges tésztához.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (102, "Steak", 290, 20, "Magyarország", "Grill és sült húsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (103, "Steakbors", 290, 20, "Magyarország", "Grill és sült húsok ízesítéséhez, pácolásához.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (104, "Sültburgonya", 290, 30, "Magyarország", "Sültburgonya ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (105, "Sültcsirke", 290, 20, "Magyarország", "Sült szárnyashúsok ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (106, "Sülthal", 290, 20, "Magyarország", "Sült hal készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (107, "Svájci steak", 330, 20, "Magyarország", "Grillhúsok, elsősorban marhahús ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (108, "Szárnyas fűszerkeverék", 290, 20, "Magyarország", "Szárnyas sült húsok, raguk ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (109, "Szezámmagos saláta", 290, 20, "Magyarország", "Salátafűszerként.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (110, "Taco", 290, 20, "Magyarország", "Mexikói ételek ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (111, "Tandoori masala", 290, 20, "Magyarország", "Indiai ételek ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (112, "Tarkabors", 390, 20, "Magyarország", "Bármilyen ételhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (113, "Tavaszi saláta", 290, 10, "Magyarország", "Saláták fűszerezésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (114, "Téli alma varázs", 350, 20, "Magyarország", "1-1,5 l forró almalé készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (115, "Thai curry", 290, 20, "Magyarország", "Thai ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (116, "Tikka masala", 290, 20, "Magyarország", "Húsokhoz és indiai ételek ízesítéséhez..");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (117, "Tzatziki", 290, 20, "Magyarország", "Tzatziki készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (118, "Tzatziki kaporral", 290, 20, "Magyarország", "Kapros tzatziki készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (119, "Vad", 290, 20, "Magyarország", "Vadhúsok ízesítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (120, "Vadpác", 320, 20, "Magyarország", "Vadhúsok pácolásához.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (121, "Vöröshagymás bors", 290, 20, "Magyarország", "Sült húsokhoz, salátákhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (122, "Vöröshagymás só", 230, 20, "Magyarország", "Sült húsok és grillek ízesítésére.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (123, "Wok", 320, 20, "Magyarország", "Wokban készülő zöldséges, tésztás ételek készítéséhez.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (124, "Zahtar", 290, 20, "Magyarország", "Közel-keleti ételekhez, olívaolajjal keverve pitához, pirítóshoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (125, "Zellersó levéllel", 220, 30, "Magyarország", "Levesekhez, sültekhez, salátákhoz.");
INSERT INTO keverek (id, nev, ar, tomeg, szarmazas, ajanlat) VALUES (126, "Zöldfűszeres grillpác", 290, 30, "Magyarország", "Grillhúsok pácolásához.");
