USE oscar;
INSERT INTO keszito (id, nev, producer) VALUES (1, "John Brabourne", 1);
INSERT INTO keszito (id, nev, producer) VALUES (2, "David Brown", 1);
INSERT INTO keszito (id, nev, producer) VALUES (3, "Jonas Rivera", 1);
INSERT INTO keszito (id, nev, producer) VALUES (4, "Peter Yates", 1);
INSERT INTO keszito (id, nev, producer) VALUES (5, "Robert Alan Aurthur", 1);
INSERT INTO keszito (id, nev, producer) VALUES (6, "Patrick J. Palmer", 1);
INSERT INTO keszito (id, nev, producer) VALUES (7, "Joseph Janni", 1);
INSERT INTO keszito (id, nev, producer) VALUES (8, "Jeremy Kleiner", 1);
INSERT INTO keszito (id, nev, producer) VALUES (9, "Marvin Worth", 1);
INSERT INTO keszito (id, nev, producer) VALUES (10, "Frank Ross", 1);
INSERT INTO keszito (id, nev, producer) VALUES (11, "James Woolf", 1);
INSERT INTO keszito (id, nev, producer) VALUES (12, "Arthur Hornblow Jr.", 1);
INSERT INTO keszito (id, nev, producer) VALUES (13, "Jon Kilik", 1);
INSERT INTO keszito (id, nev, producer) VALUES (14, "Argosy-Wanger", 0);
INSERT INTO keszito (id, nev, producer) VALUES (15, "Anthony Minghella", 1);
INSERT INTO keszito (id, nev, producer) VALUES (16, "James Mangold", 1);
INSERT INTO keszito (id, nev, producer) VALUES (17, "Ralph Nelson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (18, "Jim Sheridan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (19, "Aaron Rosenberg", 1);
INSERT INTO keszito (id, nev, producer) VALUES (20, "Ben Affleck", 1);
INSERT INTO keszito (id, nev, producer) VALUES (21, "Bob Balaban", 1);
INSERT INTO keszito (id, nev, producer) VALUES (22, "Alain Sarde", 1);
INSERT INTO keszito (id, nev, producer) VALUES (23, "Marc Platt", 1);
INSERT INTO keszito (id, nev, producer) VALUES (24, "Jerry Wald", 1);
INSERT INTO keszito (id, nev, producer) VALUES (25, "John Roberdeau", 1);
INSERT INTO keszito (id, nev, producer) VALUES (26, "Brian Currie", 1);
INSERT INTO keszito (id, nev, producer) VALUES (27, "Paramount Publix", 0);
INSERT INTO keszito (id, nev, producer) VALUES (28, "Duncan Kenworthy", 1);
INSERT INTO keszito (id, nev, producer) VALUES (29, "Patrick Palmer", 1);
INSERT INTO keszito (id, nev, producer) VALUES (30, "Michael Schaefer", 1);
INSERT INTO keszito (id, nev, producer) VALUES (31, "Marco Morabito", 1);
INSERT INTO keszito (id, nev, producer) VALUES (32, "Michael Jacobs", 1);
INSERT INTO keszito (id, nev, producer) VALUES (33, "Jeffrey Levy-Hinte", 1);
INSERT INTO keszito (id, nev, producer) VALUES (34, "Ceán Chaffin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (35, "Edward Saxon", 1);
INSERT INTO keszito (id, nev, producer) VALUES (36, "Lili Fini Zanuck", 1);
INSERT INTO keszito (id, nev, producer) VALUES (37, "Michael London", 1);
INSERT INTO keszito (id, nev, producer) VALUES (38, "Alan Marshall", 1);
INSERT INTO keszito (id, nev, producer) VALUES (39, "Feature Productions", 0);
INSERT INTO keszito (id, nev, producer) VALUES (40, "Paul Newman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (41, "Gray Frederickson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (42, "Lee Daniels", 1);
INSERT INTO keszito (id, nev, producer) VALUES (43, "Ray Stark", 1);
INSERT INTO keszito (id, nev, producer) VALUES (44, "Martin Bregman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (45, "Jeremy Dawson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (46, "Gianluigi Braschi", 1);
INSERT INTO keszito (id, nev, producer) VALUES (47, "Gabrielle Tana", 1);
INSERT INTO keszito (id, nev, producer) VALUES (48, "Michael Shamberg", 1);
INSERT INTO keszito (id, nev, producer) VALUES (49, "Stanley R. Jaffe", 1);
INSERT INTO keszito (id, nev, producer) VALUES (50, "Jonathan Sanger", 1);
INSERT INTO keszito (id, nev, producer) VALUES (51, "Michael Sugar", 1);
INSERT INTO keszito (id, nev, producer) VALUES (52, "Cy Feuer", 1);
INSERT INTO keszito (id, nev, producer) VALUES (53, "Dan Levine", 1);
INSERT INTO keszito (id, nev, producer) VALUES (54, "Paramount", 0);
INSERT INTO keszito (id, nev, producer) VALUES (55, "Charles H. Joffe", 1);
INSERT INTO keszito (id, nev, producer) VALUES (56, "Robert De Niro", 1);
INSERT INTO keszito (id, nev, producer) VALUES (57, "Bill Miller", 1);
INSERT INTO keszito (id, nev, producer) VALUES (58, "Oliver Stone", 1);
INSERT INTO keszito (id, nev, producer) VALUES (59, "Walt Disney", 1);
INSERT INTO keszito (id, nev, producer) VALUES (60, "Lawrence Weingarten", 1);
INSERT INTO keszito (id, nev, producer) VALUES (61, "Joey McFarland", 1);
INSERT INTO keszito (id, nev, producer) VALUES (62, "Melvin Frank", 1);
INSERT INTO keszito (id, nev, producer) VALUES (63, "Scott Rudin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (64, "Liberty Films", 0);
INSERT INTO keszito (id, nev, producer) VALUES (65, "Barry Spikings", 1);
INSERT INTO keszito (id, nev, producer) VALUES (66, "Kathleen Kennedy", 1);
INSERT INTO keszito (id, nev, producer) VALUES (67, "Peter Saraf", 1);
INSERT INTO keszito (id, nev, producer) VALUES (68, "Steve Golin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (69, "Walter Mirisch", 1);
INSERT INTO keszito (id, nev, producer) VALUES (70, "Leonardo DiCaprio", 1);
INSERT INTO keszito (id, nev, producer) VALUES (71, "Ceci Dempsey", 1);
INSERT INTO keszito (id, nev, producer) VALUES (72, "Samuel Goldwyn Jr.", 1);
INSERT INTO keszito (id, nev, producer) VALUES (73, "Duncan Henderson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (74, "Martin Brest", 1);
INSERT INTO keszito (id, nev, producer) VALUES (75, "Kevin Feige", 1);
INSERT INTO keszito (id, nev, producer) VALUES (76, "Harold Hecht", 1);
INSERT INTO keszito (id, nev, producer) VALUES (77, "Andy Harries", 1);
INSERT INTO keszito (id, nev, producer) VALUES (78, "Noah Baumbach", 1);
INSERT INTO keszito (id, nev, producer) VALUES (79, "Carlo Ponti", 1);
INSERT INTO keszito (id, nev, producer) VALUES (80, "Ron Yerxa", 1);
INSERT INTO keszito (id, nev, producer) VALUES (81, "The Caddo Company", 0);
INSERT INTO keszito (id, nev, producer) VALUES (82, "David Permut", 1);
INSERT INTO keszito (id, nev, producer) VALUES (83, "Richard Sakai", 1);
INSERT INTO keszito (id, nev, producer) VALUES (84, "Kevin Messick", 1);
INSERT INTO keszito (id, nev, producer) VALUES (85, "Gary Kurtz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (86, "Robert F. Colesberry", 1);
INSERT INTO keszito (id, nev, producer) VALUES (87, "Adam McKay", 1);
INSERT INTO keszito (id, nev, producer) VALUES (88, "Uberto Pasolini", 1);
INSERT INTO keszito (id, nev, producer) VALUES (89, "Michael Katz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (90, "Jenno Topping", 1);
INSERT INTO keszito (id, nev, producer) VALUES (91, "Fox", 0);
INSERT INTO keszito (id, nev, producer) VALUES (92, "Rachel Winter", 1);
INSERT INTO keszito (id, nev, producer) VALUES (93, "Jesse L. Lasky", 0);
INSERT INTO keszito (id, nev, producer) VALUES (94, "David T. Friendly", 1);
INSERT INTO keszito (id, nev, producer) VALUES (95, "Emile Sherman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (96, "Herbert Ross", 1);
INSERT INTO keszito (id, nev, producer) VALUES (97, "Charles Roven", 1);
INSERT INTO keszito (id, nev, producer) VALUES (98, "Pharrell Williams", 1);
INSERT INTO keszito (id, nev, producer) VALUES (99, "David Weisman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (100, "Selznick International Pictures", 0);
INSERT INTO keszito (id, nev, producer) VALUES (101, "Ron Howard", 1);
INSERT INTO keszito (id, nev, producer) VALUES (102, "Brad Pitt", 1);
INSERT INTO keszito (id, nev, producer) VALUES (103, "Sydney Pollack", 1);
INSERT INTO keszito (id, nev, producer) VALUES (104, "Philip S. Hobel", 1);
INSERT INTO keszito (id, nev, producer) VALUES (105, "Mark Wahlberg", 1);
INSERT INTO keszito (id, nev, producer) VALUES (106, "Richard Attenborough", 1);
INSERT INTO keszito (id, nev, producer) VALUES (107, "Cathy Schulman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (108, "Martin McDonagh", 1);
INSERT INTO keszito (id, nev, producer) VALUES (109, "Dan Janvey", 1);
INSERT INTO keszito (id, nev, producer) VALUES (110, "Callum McDougall", 1);
INSERT INTO keszito (id, nev, producer) VALUES (111, "Lee Magiday", 1);
INSERT INTO keszito (id, nev, producer) VALUES (112, "Edward Lewis", 1);
INSERT INTO keszito (id, nev, producer) VALUES (113, "Joel Coen", 1);
INSERT INTO keszito (id, nev, producer) VALUES (114, "Stephen Woolley", 1);
INSERT INTO keszito (id, nev, producer) VALUES (115, "Mihálisz Kakojánnisz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (116, "Albert S. Ruddy", 1);
INSERT INTO keszito (id, nev, producer) VALUES (117, "Alfonso Cuarón", 1);
INSERT INTO keszito (id, nev, producer) VALUES (118, "Stephen Tenenbaum", 1);
INSERT INTO keszito (id, nev, producer) VALUES (119, "Walter Wanger", 1);
INSERT INTO keszito (id, nev, producer) VALUES (120, "Charles K. Feldman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (121, "Oprah Winfrey", 1);
INSERT INTO keszito (id, nev, producer) VALUES (122, "Mel Gibson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (123, "Finola Dwyer", 1);
INSERT INTO keszito (id, nev, producer) VALUES (124, "Simon Channing-Williams", 1);
INSERT INTO keszito (id, nev, producer) VALUES (125, "Robert Benmussa", 1);
INSERT INTO keszito (id, nev, producer) VALUES (126, "Alberto Grimaldi", 1);
INSERT INTO keszito (id, nev, producer) VALUES (127, "Stanley Kramer", 1);
INSERT INTO keszito (id, nev, producer) VALUES (128, "Carl Foreman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (129, "Charles Brackett", 1);
INSERT INTO keszito (id, nev, producer) VALUES (130, "Robert Altman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (131, "Noel Pearson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (132, "Wes Anderson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (133, "Steve Starkey", 1);
INSERT INTO keszito (id, nev, producer) VALUES (134, "John Woolf", 1);
INSERT INTO keszito (id, nev, producer) VALUES (135, "Lauren Beck", 1);
INSERT INTO keszito (id, nev, producer) VALUES (136, "Gary Gilbert", 1);
INSERT INTO keszito (id, nev, producer) VALUES (137, "Eli Bush", 1);
INSERT INTO keszito (id, nev, producer) VALUES (138, "Chelsea Winstanley", 1);
INSERT INTO keszito (id, nev, producer) VALUES (139, "William Wyler", 1);
INSERT INTO keszito (id, nev, producer) VALUES (140, "J. Arthur Rank-Cineguild", 0);
INSERT INTO keszito (id, nev, producer) VALUES (141, "Saul Zaentz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (142, "Dana Brunetti", 1);
INSERT INTO keszito (id, nev, producer) VALUES (143, "Paul Webster", 1);
INSERT INTO keszito (id, nev, producer) VALUES (144, "Gary Magness", 1);
INSERT INTO keszito (id, nev, producer) VALUES (145, "Cathleen Sutherland", 1);
INSERT INTO keszito (id, nev, producer) VALUES (146, "Hal B. Wallis", 1);
INSERT INTO keszito (id, nev, producer) VALUES (147, "Dick Richards", 1);
INSERT INTO keszito (id, nev, producer) VALUES (148, "Rainbow Productions", 0);
INSERT INTO keszito (id, nev, producer) VALUES (149, "William Vince", 1);
INSERT INTO keszito (id, nev, producer) VALUES (150, "Kristi Zea", 1);
INSERT INTO keszito (id, nev, producer) VALUES (151, "Michael Mann", 1);
INSERT INTO keszito (id, nev, producer) VALUES (152, "Donna Gigliotti", 1);
INSERT INTO keszito (id, nev, producer) VALUES (153, "Carla Hacken", 1);
INSERT INTO keszito (id, nev, producer) VALUES (154, "Michael Douglas", 1);
INSERT INTO keszito (id, nev, producer) VALUES (155, "Redmond Morris", 1);
INSERT INTO keszito (id, nev, producer) VALUES (156, "Graham Broadbent", 1);
INSERT INTO keszito (id, nev, producer) VALUES (157, "Michael Nathanson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (158, "Jim Taylor", 1);
INSERT INTO keszito (id, nev, producer) VALUES (159, "Claude Berri", 1);
INSERT INTO keszito (id, nev, producer) VALUES (160, "George Stevens", 1);
INSERT INTO keszito (id, nev, producer) VALUES (161, "J. Miles Dale", 1);
INSERT INTO keszito (id, nev, producer) VALUES (162, "John Calley", 1);
INSERT INTO keszito (id, nev, producer) VALUES (163, "Kimberly Steward", 1);
INSERT INTO keszito (id, nev, producer) VALUES (164, "Robert B. Radnitz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (165, "Paul Junger Witt", 1);
INSERT INTO keszito (id, nev, producer) VALUES (166, "Kvak Sine", 1);
INSERT INTO keszito (id, nev, producer) VALUES (167, "Michael Deeley", 1);
INSERT INTO keszito (id, nev, producer) VALUES (168, "Christopher Nolan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (169, "Jan Chapman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (170, "Ridley Scott", 1);
INSERT INTO keszito (id, nev, producer) VALUES (171, "Spike Jonze", 1);
INSERT INTO keszito (id, nev, producer) VALUES (172, "Michael Gottwald", 1);
INSERT INTO keszito (id, nev, producer) VALUES (173, "Iain Canning", 1);
INSERT INTO keszito (id, nev, producer) VALUES (174, "Amy Pascal", 1);
INSERT INTO keszito (id, nev, producer) VALUES (175, "Gerald R. Molen", 1);
INSERT INTO keszito (id, nev, producer) VALUES (176, "David Puttnam", 1);
INSERT INTO keszito (id, nev, producer) VALUES (177, "Charles Chaplin Productions", 0);
INSERT INTO keszito (id, nev, producer) VALUES (178, "Taika Waititi", 1);
INSERT INTO keszito (id, nev, producer) VALUES (179, "Daniel Dubiecki", 1);
INSERT INTO keszito (id, nev, producer) VALUES (180, "David Lancaster", 1);
INSERT INTO keszito (id, nev, producer) VALUES (181, "Lawrence Gordon", 1);
INSERT INTO keszito (id, nev, producer) VALUES (182, "Gaetano Daniele", 1);
INSERT INTO keszito (id, nev, producer) VALUES (183, "Charles B. Wessler", 1);
INSERT INTO keszito (id, nev, producer) VALUES (184, "David Valdes", 1);
INSERT INTO keszito (id, nev, producer) VALUES (185, "Stephen J. Friedman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (186, "Luca Guadagnino", 1);
INSERT INTO keszito (id, nev, producer) VALUES (187, "Philip D'Antoni", 1);
INSERT INTO keszito (id, nev, producer) VALUES (188, "First National", 0);
INSERT INTO keszito (id, nev, producer) VALUES (189, "Richard Linklater", 1);
INSERT INTO keszito (id, nev, producer) VALUES (190, "Ismail Merchant", 1);
INSERT INTO keszito (id, nev, producer) VALUES (191, "Alex Rose", 1);
INSERT INTO keszito (id, nev, producer) VALUES (192, "Sean McKittrick", 1);
INSERT INTO keszito (id, nev, producer) VALUES (193, "Douglas Wick", 1);
INSERT INTO keszito (id, nev, producer) VALUES (194, "Barbra Streisand", 1);
INSERT INTO keszito (id, nev, producer) VALUES (195, "Megan Ellison", 1);
INSERT INTO keszito (id, nev, producer) VALUES (196, "Sam Spiegel", 1);
INSERT INTO keszito (id, nev, producer) VALUES (197, "Stuart Benjamin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (198, "Sam Zimbalist", 1);
INSERT INTO keszito (id, nev, producer) VALUES (199, "Sarah Siegel-Magness", 1);
INSERT INTO keszito (id, nev, producer) VALUES (200, "George Clooney", 1);
INSERT INTO keszito (id, nev, producer) VALUES (201, "Henry Ginsberg", 1);
INSERT INTO keszito (id, nev, producer) VALUES (202, "Aaron Ryder", 1);
INSERT INTO keszito (id, nev, producer) VALUES (203, "Fred Coe", 1);
INSERT INTO keszito (id, nev, producer) VALUES (204, "Richard Suckle", 1);
INSERT INTO keszito (id, nev, producer) VALUES (205, "Ross Katz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (206, "Henry Blanke", 1);
INSERT INTO keszito (id, nev, producer) VALUES (207, "Realization D'Art Cinematographique", 0);
INSERT INTO keszito (id, nev, producer) VALUES (208, "Hszü Li-kung", 1);
INSERT INTO keszito (id, nev, producer) VALUES (209, "Irwin Winkler", 1);
INSERT INTO keszito (id, nev, producer) VALUES (210, "Niki Marvin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (211, "Andrew A. Kosove", 1);
INSERT INTO keszito (id, nev, producer) VALUES (212, "Otto Preminger", 1);
INSERT INTO keszito (id, nev, producer) VALUES (213, "Eric Fellner", 1);
INSERT INTO keszito (id, nev, producer) VALUES (214, "Theodore Melfi", 1);
INSERT INTO keszito (id, nev, producer) VALUES (215, "Andrew Lazar", 1);
INSERT INTO keszito (id, nev, producer) VALUES (216, "Todd Black", 1);
INSERT INTO keszito (id, nev, producer) VALUES (217, "Mildred Lewis", 1);
INSERT INTO keszito (id, nev, producer) VALUES (218, "Sol Lesser (produkciós cég)", 0);
INSERT INTO keszito (id, nev, producer) VALUES (219, "Wendy Finerman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (220, "Debra Hayward", 1);
INSERT INTO keszito (id, nev, producer) VALUES (221, "Raymond Mansfield", 1);
INSERT INTO keszito (id, nev, producer) VALUES (222, "Warner Bros.-First National", 0);
INSERT INTO keszito (id, nev, producer) VALUES (223, "Quentin Tarantino", 1);
INSERT INTO keszito (id, nev, producer) VALUES (224, "Tony Ray", 1);
INSERT INTO keszito (id, nev, producer) VALUES (225, "Keith Redmon", 1);
INSERT INTO keszito (id, nev, producer) VALUES (226, "Steve Coogan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (227, "Caroline Baron", 1);
INSERT INTO keszito (id, nev, producer) VALUES (228, "Martin Brown", 1);
INSERT INTO keszito (id, nev, producer) VALUES (229, "Kerry Orent", 1);
INSERT INTO keszito (id, nev, producer) VALUES (230, "Gary Ross", 1);
INSERT INTO keszito (id, nev, producer) VALUES (231, "Andrew Scheinman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (232, "Paul Haggis", 1);
INSERT INTO keszito (id, nev, producer) VALUES (233, "Christine Langan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (234, "Pandro S. Berman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (235, "Alexander Payne", 1);
INSERT INTO keszito (id, nev, producer) VALUES (236, "Greg Shapiro", 1);
INSERT INTO keszito (id, nev, producer) VALUES (237, "Tom Sternberg", 1);
INSERT INTO keszito (id, nev, producer) VALUES (238, "Angie Fielder", 1);
INSERT INTO keszito (id, nev, producer) VALUES (239, "Jerome Hellman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (240, "Judie G. Hoyt", 1);
INSERT INTO keszito (id, nev, producer) VALUES (241, "Darla K. Anderson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (242, "Michael Phillips", 1);
INSERT INTO keszito (id, nev, producer) VALUES (243, "Tim Bevan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (244, "Jórgosz Lánthimosz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (245, "Richard D. Zanuck", 1);
INSERT INTO keszito (id, nev, producer) VALUES (246, "Ron Bozman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (247, "Barry Mendel", 1);
INSERT INTO keszito (id, nev, producer) VALUES (248, "James Schamus", 1);
INSERT INTO keszito (id, nev, producer) VALUES (249, "Paul Thomas Anderson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (250, "RKO Radio", 0);
INSERT INTO keszito (id, nev, producer) VALUES (251, "Elda Ferri", 1);
INSERT INTO keszito (id, nev, producer) VALUES (252, "Leland Hayward", 1);
INSERT INTO keszito (id, nev, producer) VALUES (253, "Julie Yorn", 1);
INSERT INTO keszito (id, nev, producer) VALUES (254, "J. Arthur Rank-Archers", 0);
INSERT INTO keszito (id, nev, producer) VALUES (255, "Anthony Havelock-Allan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (256, "London Films", 0);
INSERT INTO keszito (id, nev, producer) VALUES (257, "Burt Sugarman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (258, "Nora Grossman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (259, "Universal", 0);
INSERT INTO keszito (id, nev, producer) VALUES (260, "Alix Madigan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (261, "Paul Mazursky", 1);
INSERT INTO keszito (id, nev, producer) VALUES (262, "20th Century", 0);
INSERT INTO keszito (id, nev, producer) VALUES (263, "Shannon McIntosh", 1);
INSERT INTO keszito (id, nev, producer) VALUES (264, "John Huston", 1);
INSERT INTO keszito (id, nev, producer) VALUES (265, "Edward Zwick", 1);
INSERT INTO keszito (id, nev, producer) VALUES (266, "Arthur Laurents", 1);
INSERT INTO keszito (id, nev, producer) VALUES (267, "Scott Franklin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (268, "Ang Lee", 1);
INSERT INTO keszito (id, nev, producer) VALUES (269, "Ingo Preminger", 1);
INSERT INTO keszito (id, nev, producer) VALUES (270, "Howard G. Minsky", 1);
INSERT INTO keszito (id, nev, producer) VALUES (271, "Evelyn O'Neill", 1);
INSERT INTO keszito (id, nev, producer) VALUES (272, "Cameron Mackintosh", 1);
INSERT INTO keszito (id, nev, producer) VALUES (273, "Bridget Johnson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (274, "Vittorio Cecchi Gori", 1);
INSERT INTO keszito (id, nev, producer) VALUES (275, "Taylor Hackford", 1);
INSERT INTO keszito (id, nev, producer) VALUES (276, "Samuel Goldwyn Productions", 0);
INSERT INTO keszito (id, nev, producer) VALUES (277, "Todd Phillips", 1);
INSERT INTO keszito (id, nev, producer) VALUES (278, "Kit Golden", 1);
INSERT INTO keszito (id, nev, producer) VALUES (279, "Metro-Goldwyn-Mayer", 0);
INSERT INTO keszito (id, nev, producer) VALUES (280, "Pong Dzsunho", 1);
INSERT INTO keszito (id, nev, producer) VALUES (281, "A. Kitman Ho", 1);
INSERT INTO keszito (id, nev, producer) VALUES (282, "Josh Penn", 1);
INSERT INTO keszito (id, nev, producer) VALUES (283, "Simon Kinberg", 1);
INSERT INTO keszito (id, nev, producer) VALUES (284, "Peter Morgan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (285, "Kathryn Bigelow", 1);
INSERT INTO keszito (id, nev, producer) VALUES (286, "John Smithson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (287, "Hal Roach (produkciós cég)", 0);
INSERT INTO keszito (id, nev, producer) VALUES (288, "Steven M. Rales", 1);
INSERT INTO keszito (id, nev, producer) VALUES (289, "Fred Kohlmar", 1);
INSERT INTO keszito (id, nev, producer) VALUES (290, "Bruce Gilbert", 1);
INSERT INTO keszito (id, nev, producer) VALUES (291, "Reginald Hudlin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (292, "David Hoberman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (293, "Ivan Reitman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (294, "Bruce Cohen", 1);
INSERT INTO keszito (id, nev, producer) VALUES (295, "Jennifer Fox", 1);
INSERT INTO keszito (id, nev, producer) VALUES (296, "Joshua Logan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (297, "William Perlberg", 1);
INSERT INTO keszito (id, nev, producer) VALUES (298, "Peter Chernin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (299, "Alan J. Pakula", 1);
INSERT INTO keszito (id, nev, producer) VALUES (300, "Emilie Georges", 1);
INSERT INTO keszito (id, nev, producer) VALUES (301, "Denzel Washington", 1);
INSERT INTO keszito (id, nev, producer) VALUES (302, "Alejandro G. Iñárritu", 1);
INSERT INTO keszito (id, nev, producer) VALUES (303, "Baz Luhrmann", 1);
INSERT INTO keszito (id, nev, producer) VALUES (304, "Amanda Posey", 1);
INSERT INTO keszito (id, nev, producer) VALUES (305, "Jon Landau", 1);
INSERT INTO keszito (id, nev, producer) VALUES (306, "Frank Darabont", 1);
INSERT INTO keszito (id, nev, producer) VALUES (307, "Rob Reiner", 1);
INSERT INTO keszito (id, nev, producer) VALUES (308, "Matt Damon", 1);
INSERT INTO keszito (id, nev, producer) VALUES (309, "Stanley Kubrick", 1);
INSERT INTO keszito (id, nev, producer) VALUES (310, "Stefan Arndt", 1);
INSERT INTO keszito (id, nev, producer) VALUES (311, "Bill Gerber", 1);
INSERT INTO keszito (id, nev, producer) VALUES (312, "Mark Boal", 1);
INSERT INTO keszito (id, nev, producer) VALUES (313, "Lindsay Doran", 1);
INSERT INTO keszito (id, nev, producer) VALUES (314, "Norman Jewison", 1);
INSERT INTO keszito (id, nev, producer) VALUES (315, "Cecil B. DeMille", 1);
INSERT INTO keszito (id, nev, producer) VALUES (316, "Ian Bryce", 1);
INSERT INTO keszito (id, nev, producer) VALUES (317, "George Miller", 1);
INSERT INTO keszito (id, nev, producer) VALUES (318, "Todd Field", 1);
INSERT INTO keszito (id, nev, producer) VALUES (319, "Nellie Bellflower", 1);
INSERT INTO keszito (id, nev, producer) VALUES (320, "Margaret Menegoz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (321, "Jim Burke", 1);
INSERT INTO keszito (id, nev, producer) VALUES (322, "Arthur Freed", 1);
INSERT INTO keszito (id, nev, producer) VALUES (323, "Sarah Green", 1);
INSERT INTO keszito (id, nev, producer) VALUES (324, "Dede Gardner", 1);
INSERT INTO keszito (id, nev, producer) VALUES (325, "Anthony Katagas", 1);
INSERT INTO keszito (id, nev, producer) VALUES (326, "Sherry Lansing", 1);
INSERT INTO keszito (id, nev, producer) VALUES (327, "Frederick Zollo", 1);
INSERT INTO keszito (id, nev, producer) VALUES (328, "Nicole Rocklin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (329, "Martin Richards", 1);
INSERT INTO keszito (id, nev, producer) VALUES (330, "Nick Vallelonga", 1);
INSERT INTO keszito (id, nev, producer) VALUES (331, "Kenneth Utt", 1);
INSERT INTO keszito (id, nev, producer) VALUES (332, "Chris Moore", 1);
INSERT INTO keszito (id, nev, producer) VALUES (333, "Mary Parent", 1);
INSERT INTO keszito (id, nev, producer) VALUES (334, "Peter Jackson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (335, "Steven Spielberg", 1);
INSERT INTO keszito (id, nev, producer) VALUES (336, "Stacey Sher", 1);
INSERT INTO keszito (id, nev, producer) VALUES (337, "Martin Scorsese", 1);
INSERT INTO keszito (id, nev, producer) VALUES (338, "Brian Oliver", 1);
INSERT INTO keszito (id, nev, producer) VALUES (339, "Roman Polański", 1);
INSERT INTO keszito (id, nev, producer) VALUES (340, "Howard Gottfried", 1);
INSERT INTO keszito (id, nev, producer) VALUES (341, "John Houseman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (342, "Jason Reitman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (343, "Walter Coblenz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (344, "Adele Romanski", 1);
INSERT INTO keszito (id, nev, producer) VALUES (345, "Tracey Seaward", 1);
INSERT INTO keszito (id, nev, producer) VALUES (346, "Mario Cecchi Gori", 1);
INSERT INTO keszito (id, nev, producer) VALUES (347, "Ed Guiney", 1);
INSERT INTO keszito (id, nev, producer) VALUES (348, "Letty Aronson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (349, "Timothy Burrill", 1);
INSERT INTO keszito (id, nev, producer) VALUES (350, "Buddy Adler", 1);
INSERT INTO keszito (id, nev, producer) VALUES (351, "Frank McCarthy", 1);
INSERT INTO keszito (id, nev, producer) VALUES (352, "Fred Baron", 1);
INSERT INTO keszito (id, nev, producer) VALUES (353, "Pilar Savone", 1);
INSERT INTO keszito (id, nev, producer) VALUES (354, "Ortus", 0);
INSERT INTO keszito (id, nev, producer) VALUES (355, "Jim Wilson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (356, "Christian Colson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (357, "Peter Weir", 1);
INSERT INTO keszito (id, nev, producer) VALUES (358, "Julian Krainin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (359, "J. Arthur Rank-Two Cities Films", 0);
INSERT INTO keszito (id, nev, producer) VALUES (360, "Tamara Asseyev", 1);
INSERT INTO keszito (id, nev, producer) VALUES (361, "Fred Roos", 1);
INSERT INTO keszito (id, nev, producer) VALUES (362, "Daniel Lupi", 1);
INSERT INTO keszito (id, nev, producer) VALUES (363, "Bill Pohlad", 1);
INSERT INTO keszito (id, nev, producer) VALUES (364, "Mark Huffam", 1);
INSERT INTO keszito (id, nev, producer) VALUES (365, "Ingmar Bergman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (366, "Billy Wilder", 1);
INSERT INTO keszito (id, nev, producer) VALUES (367, "Helen Estabrook", 1);
INSERT INTO keszito (id, nev, producer) VALUES (368, "Carthew Neal", 1);
INSERT INTO keszito (id, nev, producer) VALUES (369, "David Heyman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (370, "Warner Bros.", 0);
INSERT INTO keszito (id, nev, producer) VALUES (371, "Lisa Weinstein", 1);
INSERT INTO keszito (id, nev, producer) VALUES (372, "Michael Cimino", 1);
INSERT INTO keszito (id, nev, producer) VALUES (373, "Arnold Kopelson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (374, "John Boorman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (375, "Fred Berger", 1);
INSERT INTO keszito (id, nev, producer) VALUES (376, "Two Cities Films", 0);
INSERT INTO keszito (id, nev, producer) VALUES (377, "Ross Hunter", 1);
INSERT INTO keszito (id, nev, producer) VALUES (378, "Michael Ohoven", 1);
INSERT INTO keszito (id, nev, producer) VALUES (379, "Emma Thomas", 1);
INSERT INTO keszito (id, nev, producer) VALUES (380, "Michael Grillo", 1);
INSERT INTO keszito (id, nev, producer) VALUES (381, "Vincent Landay", 1);
INSERT INTO keszito (id, nev, producer) VALUES (382, "Michael Todd", 1);
INSERT INTO keszito (id, nev, producer) VALUES (383, "Francis Ford Coppola", 1);
INSERT INTO keszito (id, nev, producer) VALUES (384, "Kristie Macosko Krieger", 1);
INSERT INTO keszito (id, nev, producer) VALUES (385, "Grant Hill", 1);
INSERT INTO keszito (id, nev, producer) VALUES (386, "Guillermo del Toro", 1);
INSERT INTO keszito (id, nev, producer) VALUES (387, "Gary Levinsohn", 1);
INSERT INTO keszito (id, nev, producer) VALUES (388, "Steve McQueen", 1);
INSERT INTO keszito (id, nev, producer) VALUES (389, "Ahmed Rachedi", 1);
INSERT INTO keszito (id, nev, producer) VALUES (390, "Marshall Herskovitz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (391, "Mike Medavoy", 1);
INSERT INTO keszito (id, nev, producer) VALUES (392, "Jane Scott", 1);
INSERT INTO keszito (id, nev, producer) VALUES (393, "Kevin J. Walsh", 1);
INSERT INTO keszito (id, nev, producer) VALUES (394, "John Ford", 1);
INSERT INTO keszito (id, nev, producer) VALUES (395, "Lianne Halfon", 1);
INSERT INTO keszito (id, nev, producer) VALUES (396, "John Foreman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (397, "20th Century-Fox", 0);
INSERT INTO keszito (id, nev, producer) VALUES (398, "Chris Columbus", 1);
INSERT INTO keszito (id, nev, producer) VALUES (399, "Tony Richardson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (400, "David Levy", 1);
INSERT INTO keszito (id, nev, producer) VALUES (401, "Pieter Jan Brugge", 1);
INSERT INTO keszito (id, nev, producer) VALUES (402, "Alejandro González Iñárritu", 1);
INSERT INTO keszito (id, nev, producer) VALUES (403, "Martin Poll", 1);
INSERT INTO keszito (id, nev, producer) VALUES (404, "Jack Cummings", 1);
INSERT INTO keszito (id, nev, producer) VALUES (405, "Teddy Schwarzman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (406, "Brian Grazer", 1);
INSERT INTO keszito (id, nev, producer) VALUES (407, "Alan Ladd Jr.", 1);
INSERT INTO keszito (id, nev, producer) VALUES (408, "Curtis Hanson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (409, "Paramount Famous Lasky", 0);
INSERT INTO keszito (id, nev, producer) VALUES (410, "Harvey Weinstein", 1);
INSERT INTO keszito (id, nev, producer) VALUES (411, "James Cameron", 1);
INSERT INTO keszito (id, nev, producer) VALUES (412, "Bradley Cooper", 1);
INSERT INTO keszito (id, nev, producer) VALUES (413, "Jack L. Warner", 1);
INSERT INTO keszito (id, nev, producer) VALUES (414, "Hank Moonjean", 1);
INSERT INTO keszito (id, nev, producer) VALUES (415, "Sol C. Siegel", 1);
INSERT INTO keszito (id, nev, producer) VALUES (416, "Jordan Peele", 1);
INSERT INTO keszito (id, nev, producer) VALUES (417, "Columbia", 0);
INSERT INTO keszito (id, nev, producer) VALUES (418, "Grant Heslov", 1);
INSERT INTO keszito (id, nev, producer) VALUES (419, "Charles Gordon", 1);
INSERT INTO keszito (id, nev, producer) VALUES (420, "Bernard Smith", 1);
INSERT INTO keszito (id, nev, producer) VALUES (421, "Gil Netter", 1);
INSERT INTO keszito (id, nev, producer) VALUES (422, "Frank Marshall", 1);
INSERT INTO keszito (id, nev, producer) VALUES (423, "Michael Nozik", 1);
INSERT INTO keszito (id, nev, producer) VALUES (424, "Richard Wechsler", 1);
INSERT INTO keszito (id, nev, producer) VALUES (425, "Richard N. Gladstein", 1);
INSERT INTO keszito (id, nev, producer) VALUES (426, "Sam Mendes", 1);
INSERT INTO keszito (id, nev, producer) VALUES (427, "Ronald L. Schwary", 1);
INSERT INTO keszito (id, nev, producer) VALUES (428, "Jane Rosenthal", 1);
INSERT INTO keszito (id, nev, producer) VALUES (429, "Jeremy Thomas", 1);
INSERT INTO keszito (id, nev, producer) VALUES (430, "Ethan Coen", 1);
INSERT INTO keszito (id, nev, producer) VALUES (431, "Pippa Harris", 1);
INSERT INTO keszito (id, nev, producer) VALUES (432, "Fran Walsh", 1);
INSERT INTO keszito (id, nev, producer) VALUES (433, "James W. Skotchdopole", 1);
INSERT INTO keszito (id, nev, producer) VALUES (434, "Don Hahn", 1);
INSERT INTO keszito (id, nev, producer) VALUES (435, "William Kong", 1);
INSERT INTO keszito (id, nev, producer) VALUES (436, "Lawrence Lasker", 1);
INSERT INTO keszito (id, nev, producer) VALUES (437, "Lynette Howell Taylor", 1);
INSERT INTO keszito (id, nev, producer) VALUES (438, "John Wayne", 1);
INSERT INTO keszito (id, nev, producer) VALUES (439, "Bill Walsh", 1);
INSERT INTO keszito (id, nev, producer) VALUES (440, "Quincy Jones", 1);
INSERT INTO keszito (id, nev, producer) VALUES (441, "Bernard Schwartz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (442, "Bill Mechanic", 1);
INSERT INTO keszito (id, nev, producer) VALUES (443, "Elia Kazan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (444, "Rachael Horovitz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (445, "Tony Thomas", 1);
INSERT INTO keszito (id, nev, producer) VALUES (446, "Steve Tisch", 1);
INSERT INTO keszito (id, nev, producer) VALUES (447, "Charles Okun", 1);
INSERT INTO keszito (id, nev, producer) VALUES (448, "Norma Heyman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (449, "Tony Bill", 1);
INSERT INTO keszito (id, nev, producer) VALUES (450, "Bruce Davey", 1);
INSERT INTO keszito (id, nev, producer) VALUES (451, "Henry Fonda and Reginald Rose", 1);
INSERT INTO keszito (id, nev, producer) VALUES (452, "Jonathan Gordon", 1);
INSERT INTO keszito (id, nev, producer) VALUES (453, "James L. Brooks", 1);
INSERT INTO keszito (id, nev, producer) VALUES (454, "Doug Mitchell", 1);
INSERT INTO keszito (id, nev, producer) VALUES (455, "Douglas Urbanski", 1);
INSERT INTO keszito (id, nev, producer) VALUES (456, "Robbie Brenner", 1);
INSERT INTO keszito (id, nev, producer) VALUES (457, "Anatole Litvak", 1);
INSERT INTO keszito (id, nev, producer) VALUES (458, "Dan Jinks", 1);
INSERT INTO keszito (id, nev, producer) VALUES (459, "Emma Tillinger Koskoff", 1);
INSERT INTO keszito (id, nev, producer) VALUES (460, "Blye Pagon Faust", 1);
INSERT INTO keszito (id, nev, producer) VALUES (461, "Bengt Forslund", 1);
INSERT INTO keszito (id, nev, producer) VALUES (462, "William Goetz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (463, "Barry Levinson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (464, "Jacques Perrin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (465, "Anne Rosellini", 1);
INSERT INTO keszito (id, nev, producer) VALUES (466, "Robert Fox", 1);
INSERT INTO keszito (id, nev, producer) VALUES (467, "Arlene Donovan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (468, "Steven Haft", 1);
INSERT INTO keszito (id, nev, producer) VALUES (469, "Albert Berger", 1);
INSERT INTO keszito (id, nev, producer) VALUES (470, "Lawrence Kasdan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (471, "Howard Baldwin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (472, "Walter Wanger (produkciós cég)", 0);
INSERT INTO keszito (id, nev, producer) VALUES (473, "Jason Blum", 1);
INSERT INTO keszito (id, nev, producer) VALUES (474, "Tom Rosenberg", 1);
INSERT INTO keszito (id, nev, producer) VALUES (475, "Marc Norman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (476, "Andrew S. Karsch", 1);
INSERT INTO keszito (id, nev, producer) VALUES (477, "Brunson Green", 1);
INSERT INTO keszito (id, nev, producer) VALUES (478, "Fred Zinnemann", 1);
INSERT INTO keszito (id, nev, producer) VALUES (479, "Mark Johnson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (480, "Ernest Lehman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (481, "Fernando Ghia", 1);
INSERT INTO keszito (id, nev, producer) VALUES (482, "Gareth Unwin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (483, "Celine Rattray", 1);
INSERT INTO keszito (id, nev, producer) VALUES (484, "Richard Roth", 1);
INSERT INTO keszito (id, nev, producer) VALUES (485, "Robert Lorenz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (486, "Carolynne Cunningham", 1);
INSERT INTO keszito (id, nev, producer) VALUES (487, "Russell Smith", 1);
INSERT INTO keszito (id, nev, producer) VALUES (488, "Robert Greenhut", 1);
INSERT INTO keszito (id, nev, producer) VALUES (489, "Morton DaCosta", 1);
INSERT INTO keszito (id, nev, producer) VALUES (490, "Darryl F. Zanuck", 1);
INSERT INTO keszito (id, nev, producer) VALUES (491, "Merian C. Cooper", 1);
INSERT INTO keszito (id, nev, producer) VALUES (492, "Ido Ostrowsky", 1);
INSERT INTO keszito (id, nev, producer) VALUES (493, "Richard B. Goodwin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (494, "Edward S. Feldman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (495, "Leslie Holleran", 1);
INSERT INTO keszito (id, nev, producer) VALUES (496, "Robert Rossen", 1);
INSERT INTO keszito (id, nev, producer) VALUES (497, "Julia Phillips", 1);
INSERT INTO keszito (id, nev, producer) VALUES (498, "Branko Lustig", 1);
INSERT INTO keszito (id, nev, producer) VALUES (499, "Danny DeVito", 1);
INSERT INTO keszito (id, nev, producer) VALUES (500, "Cosmopolitan", 0);
INSERT INTO keszito (id, nev, producer) VALUES (501, "Gabriela Rodríguez", 1);
INSERT INTO keszito (id, nev, producer) VALUES (502, "Jordan Horowitz", 1);
INSERT INTO keszito (id, nev, producer) VALUES (503, "Shawn Levy", 1);
INSERT INTO keszito (id, nev, producer) VALUES (504, "Broderick Johnson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (505, "William Peter Blatty", 1);
INSERT INTO keszito (id, nev, producer) VALUES (506, "Diana Ossana", 1);
INSERT INTO keszito (id, nev, producer) VALUES (507, "David Franzoni", 1);
INSERT INTO keszito (id, nev, producer) VALUES (508, "Pete Czernin", 1);
INSERT INTO keszito (id, nev, producer) VALUES (509, "Graham Leader", 1);
INSERT INTO keszito (id, nev, producer) VALUES (510, "Bob Rafelson", 1);
INSERT INTO keszito (id, nev, producer) VALUES (511, "David Parfitt", 1);
INSERT INTO keszito (id, nev, producer) VALUES (512, "Martin Elfand", 1);
INSERT INTO keszito (id, nev, producer) VALUES (513, "Lawrence Turman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (514, "Robert Evans", 1);
INSERT INTO keszito (id, nev, producer) VALUES (515, "David Womark", 1);
INSERT INTO keszito (id, nev, producer) VALUES (516, "Mike Nichols", 1);
INSERT INTO keszito (id, nev, producer) VALUES (517, "Arnon Milchan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (518, "JoAnne Sellar", 1);
INSERT INTO keszito (id, nev, producer) VALUES (519, "Kevin Costner", 1);
INSERT INTO keszito (id, nev, producer) VALUES (520, "Peter Spears", 1);
INSERT INTO keszito (id, nev, producer) VALUES (521, "Graham King", 1);
INSERT INTO keszito (id, nev, producer) VALUES (522, "Robert Rossen Productions", 0);
INSERT INTO keszito (id, nev, producer) VALUES (523, "Robert Chartoff", 1);
INSERT INTO keszito (id, nev, producer) VALUES (524, "Denis Héroux", 1);
INSERT INTO keszito (id, nev, producer) VALUES (525, "Robert Wise", 1);
INSERT INTO keszito (id, nev, producer) VALUES (526, "David Linde", 1);
INSERT INTO keszito (id, nev, producer) VALUES (527, "Clint Eastwood", 1);
INSERT INTO keszito (id, nev, producer) VALUES (528, "Michael Barnathan", 1);
INSERT INTO keszito (id, nev, producer) VALUES (529, "John Lesher", 1);
INSERT INTO keszito (id, nev, producer) VALUES (530, "Marc Turtletaub", 1);
INSERT INTO keszito (id, nev, producer) VALUES (531, "Alison Owen", 1);
INSERT INTO keszito (id, nev, producer) VALUES (532, "Edward H. Hamm Jr.", 1);
INSERT INTO keszito (id, nev, producer) VALUES (533, "John Peverall", 1);
INSERT INTO keszito (id, nev, producer) VALUES (534, "Anthony McCarten", 1);
INSERT INTO keszito (id, nev, producer) VALUES (535, "Walter Parkes", 1);
INSERT INTO keszito (id, nev, producer) VALUES (536, "Robert Redford", 1);
INSERT INTO keszito (id, nev, producer) VALUES (537, "Laurence Mark", 1);
INSERT INTO keszito (id, nev, producer) VALUES (538, "Robert Michael Geisler", 1);
INSERT INTO keszito (id, nev, producer) VALUES (539, "Jayne-Ann Tenggren", 1);
INSERT INTO keszito (id, nev, producer) VALUES (540, "Danny Boyle", 1);
INSERT INTO keszito (id, nev, producer) VALUES (541, "Robert F. Blumofe and Harold Leventhal", 1);
INSERT INTO keszito (id, nev, producer) VALUES (542, "Lewis Gilbert", 1);
INSERT INTO keszito (id, nev, producer) VALUES (543, "Warren Beatty", 1);
INSERT INTO keszito (id, nev, producer) VALUES (544, "Peter Farrelly", 1);
INSERT INTO keszito (id, nev, producer) VALUES (545, "Irwin Allen", 1);
INSERT INTO keszito (id, nev, producer) VALUES (546, "Cameron Crowe", 1);
INSERT INTO keszito (id, nev, producer) VALUES (547, "Michael De Luca", 1);
INSERT INTO keszito (id, nev, producer) VALUES (548, "Lawrence Bender", 1);
INSERT INTO keszito (id, nev, producer) VALUES (549, "Veit Heiduschka", 1);
INSERT INTO keszito (id, nev, producer) VALUES (550, "Todd Lieberman", 1);
INSERT INTO keszito (id, nev, producer) VALUES (551, "Mason Novick", 1);
INSERT INTO keszito (id, nev, producer) VALUES (552, "Nicolas Chartier", 1);
INSERT INTO keszito (id, nev, producer) VALUES (553, "Mercury", 0);
INSERT INTO keszito (id, nev, producer) VALUES (554, "Mark Gordon", 1);
INSERT INTO keszito (id, nev, producer) VALUES (555, "Sofia Coppola", 1);
INSERT INTO keszito (id, nev, producer) VALUES (556, "Laura Bickford", 1);
INSERT INTO keszito (id, nev, producer) VALUES (557, "Arthur P. Jacobs", 1);
INSERT INTO keszito (id, nev, producer) VALUES (558, "Barrie M. Osborne", 1);
INSERT INTO keszito (id, nev, producer) VALUES (559, "and Barry Mendel", 1);
INSERT INTO keszito (id, nev, producer) VALUES (560, "Thomas Langmann", 1);
INSERT INTO keszito (id, nev, producer) VALUES (561, "Lisa Bruce", 1);
INSERT INTO keszito (id, nev, producer) VALUES (562, "Spike Lee", 1);
