USE fuszerkeverek;
INSERT INTO osszetevo (id, nev) VALUES (1, "alma");
INSERT INTO osszetevo (id, nev) VALUES (2, "ánizs");
INSERT INTO osszetevo (id, nev) VALUES (3, "ánizsmag");
INSERT INTO osszetevo (id, nev) VALUES (4, "babér");
INSERT INTO osszetevo (id, nev) VALUES (5, "babérlevél");
INSERT INTO osszetevo (id, nev) VALUES (6, "barnacukor");
INSERT INTO osszetevo (id, nev) VALUES (7, "bazsalikom");
INSERT INTO osszetevo (id, nev) VALUES (8, "borókabogyó");
INSERT INTO osszetevo (id, nev) VALUES (9, "bors");
INSERT INTO osszetevo (id, nev) VALUES (10, "borsikafű");
INSERT INTO osszetevo (id, nev) VALUES (11, "burgonyakeményítő");
INSERT INTO osszetevo (id, nev) VALUES (12, "burgonyapehely");
INSERT INTO osszetevo (id, nev) VALUES (13, "Cayenne-bors");
INSERT INTO osszetevo (id, nev) VALUES (14, "chili");
INSERT INTO osszetevo (id, nev) VALUES (15, "chilipor");
INSERT INTO osszetevo (id, nev) VALUES (16, "citromfű");
INSERT INTO osszetevo (id, nev) VALUES (17, "citromhéj");
INSERT INTO osszetevo (id, nev) VALUES (18, "citrompor");
INSERT INTO osszetevo (id, nev) VALUES (19, "citromsav");
INSERT INTO osszetevo (id, nev) VALUES (20, "cukor");
INSERT INTO osszetevo (id, nev) VALUES (21, "curry");
INSERT INTO osszetevo (id, nev) VALUES (22, "csillagánizs");
INSERT INTO osszetevo (id, nev) VALUES (23, "édeskömény");
INSERT INTO osszetevo (id, nev) VALUES (24, "fahéj");
INSERT INTO osszetevo (id, nev) VALUES (25, "fahéjvirág");
INSERT INTO osszetevo (id, nev) VALUES (26, "fehér szezámmag");
INSERT INTO osszetevo (id, nev) VALUES (27, "fehérbors");
INSERT INTO osszetevo (id, nev) VALUES (28, "fekete szezámmag");
INSERT INTO osszetevo (id, nev) VALUES (29, "feketebors");
INSERT INTO osszetevo (id, nev) VALUES (31, "fokhagyma");
INSERT INTO osszetevo (id, nev) VALUES (32, "fokhagymagranulátum");
INSERT INTO osszetevo (id, nev) VALUES (33, "füstölt paprika");
INSERT INTO osszetevo (id, nev) VALUES (34, "füstölt só");
INSERT INTO osszetevo (id, nev) VALUES (35, "füstsó");
INSERT INTO osszetevo (id, nev) VALUES (36, "fűszerpaprika");
INSERT INTO osszetevo (id, nev) VALUES (37, "garam masala");
INSERT INTO osszetevo (id, nev) VALUES (38, "görögszéna");
INSERT INTO osszetevo (id, nev) VALUES (39, "görögszénamag");
INSERT INTO osszetevo (id, nev) VALUES (40, "guineai bors");
INSERT INTO osszetevo (id, nev) VALUES (41, "gyömbér");
INSERT INTO osszetevo (id, nev) VALUES (42, "hagyma");
INSERT INTO osszetevo (id, nev) VALUES (43, "hibiszkusz");
INSERT INTO osszetevo (id, nev) VALUES (44, "kakukkfű");
INSERT INTO osszetevo (id, nev) VALUES (45, "kapor");
INSERT INTO osszetevo (id, nev) VALUES (46, "kaporlevél");
INSERT INTO osszetevo (id, nev) VALUES (47, "kapormag");
INSERT INTO osszetevo (id, nev) VALUES (48, "kardamom");
INSERT INTO osszetevo (id, nev) VALUES (49, "kávé");
INSERT INTO osszetevo (id, nev) VALUES (50, "koriander");
INSERT INTO osszetevo (id, nev) VALUES (51, "korianderlevél");
INSERT INTO osszetevo (id, nev) VALUES (52, "koriandermag");
INSERT INTO osszetevo (id, nev) VALUES (53, "kömény");
INSERT INTO osszetevo (id, nev) VALUES (54, "köménymag");
INSERT INTO osszetevo (id, nev) VALUES (55, "krétai vad bazsalikom");
INSERT INTO osszetevo (id, nev) VALUES (56, "krétai vad kakukkfű");
INSERT INTO osszetevo (id, nev) VALUES (57, "krétai vad majoranna");
INSERT INTO osszetevo (id, nev) VALUES (58, "krétai vad oregánó");
INSERT INTO osszetevo (id, nev) VALUES (59, "krétai vad rozmaring");
INSERT INTO osszetevo (id, nev) VALUES (60, "kubebabors");
INSERT INTO osszetevo (id, nev) VALUES (61, "kukoricadara");
INSERT INTO osszetevo (id, nev) VALUES (62, "kurkuma");
INSERT INTO osszetevo (id, nev) VALUES (63, "lestyán");
INSERT INTO osszetevo (id, nev) VALUES (64, "levendula");
INSERT INTO osszetevo (id, nev) VALUES (65, "majoranna");
INSERT INTO osszetevo (id, nev) VALUES (66, "mák");
INSERT INTO osszetevo (id, nev) VALUES (67, "menta");
INSERT INTO osszetevo (id, nev) VALUES (68, "mustármag");
INSERT INTO osszetevo (id, nev) VALUES (69, "nádcukor");
INSERT INTO osszetevo (id, nev) VALUES (70, "narancshéj");
INSERT INTO osszetevo (id, nev) VALUES (71, "nigella");
INSERT INTO osszetevo (id, nev) VALUES (72, "nori");
INSERT INTO osszetevo (id, nev) VALUES (73, "oregánó");
INSERT INTO osszetevo (id, nev) VALUES (74, "paprika");
INSERT INTO osszetevo (id, nev) VALUES (75, "paradicsom");
INSERT INTO osszetevo (id, nev) VALUES (76, "paszternák");
INSERT INTO osszetevo (id, nev) VALUES (77, "petrezselyem");
INSERT INTO osszetevo (id, nev) VALUES (78, "petrezselyemgyökér");
INSERT INTO osszetevo (id, nev) VALUES (79, "petrezselyemlevél");
INSERT INTO osszetevo (id, nev) VALUES (80, "piros pritaminpaprika");
INSERT INTO osszetevo (id, nev) VALUES (81, "póré");
INSERT INTO osszetevo (id, nev) VALUES (82, "pritamin");
INSERT INTO osszetevo (id, nev) VALUES (83, "pritaminpaprika");
INSERT INTO osszetevo (id, nev) VALUES (84, "római kömény");
INSERT INTO osszetevo (id, nev) VALUES (85, "rozmaring");
INSERT INTO osszetevo (id, nev) VALUES (86, "rózsabors");
INSERT INTO osszetevo (id, nev) VALUES (87, "sáfrány");
INSERT INTO osszetevo (id, nev) VALUES (88, "sáfrányos szeklice");
INSERT INTO osszetevo (id, nev) VALUES (89, "sárgarépa");
INSERT INTO osszetevo (id, nev) VALUES (90, "snidling");
INSERT INTO osszetevo (id, nev) VALUES (91, "só");
INSERT INTO osszetevo (id, nev) VALUES (92, "sumach");
INSERT INTO osszetevo (id, nev) VALUES (93, "szecsuáni bors");
INSERT INTO osszetevo (id, nev) VALUES (94, "szegfűbors");
INSERT INTO osszetevo (id, nev) VALUES (95, "szegfűszeg");
INSERT INTO osszetevo (id, nev) VALUES (96, "szerecsendió");
INSERT INTO osszetevo (id, nev) VALUES (97, "szerecsendióvirág");
INSERT INTO osszetevo (id, nev) VALUES (98, "szezámmag");
INSERT INTO osszetevo (id, nev) VALUES (99, "tárkony");
INSERT INTO osszetevo (id, nev) VALUES (100, "tengeri só");
INSERT INTO osszetevo (id, nev) VALUES (101, "tormapor");
INSERT INTO osszetevo (id, nev) VALUES (102, "turbolya");
INSERT INTO osszetevo (id, nev) VALUES (103, "vanília");
INSERT INTO osszetevo (id, nev) VALUES (104, "vöröshagyma");
INSERT INTO osszetevo (id, nev) VALUES (105, "zeller");
INSERT INTO osszetevo (id, nev) VALUES (106, "zellergyökér");
INSERT INTO osszetevo (id, nev) VALUES (107, "zellerlevél");
INSERT INTO osszetevo (id, nev) VALUES (108, "zöldbors");
INSERT INTO osszetevo (id, nev) VALUES (109, "zöldség");
INSERT INTO osszetevo (id, nev) VALUES (110, "zöldségek");
INSERT INTO osszetevo (id, nev) VALUES (111, "zöldségkeverék");
INSERT INTO osszetevo (id, nev) VALUES (112, "zsálya");
